spring:
  datasource:
    url: jdbc:mysql://18.233.255.172:3306/edusys_01?useUnicode=true&characterEncoding=UTF-8&usessL=false
    username: root
    password: Tianshui#2025!
    driver-class-name: com.mysgl.cj.jdbc.Driver
server:
  port: 8082
